# Generated by Django 5.1.6 on 2025-03-02 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='store',
        ),
    ]
