# Generated by Django 5.1.6 on 2025-03-04 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_receipt'),
        ('users', '0005_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='trader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.trader'),
        ),
    ]
