# Generated by Django 5.1.6 on 2025-03-04 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_purchaserequest_trader'),
        ('users', '0005_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
    ]
